### ISSUE TITLE
Automate APK signing

### ISSUE THREAD

**Issue by pnobbe** [Laixer/Swabbr-Android#57]
## [Sign and align an Android APK](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops)

If your build does not already [sign and zipalign](https://developer.android.com/studio/publish/app-signing) the APK,add the [Android Signing](../tasks/build/android-signing.md) task to the YAML. An APK must be signed to run on a device instead of an emulator. Zipaligning reduces the RAM consumed by the app.

<blockquote><strong>Important: </strong>We recommend storing each of the following passwords in a <a href="../process/variables.md#secret-variables" data-raw-source="[secret variable](../process/variables.md#secret-variables)">secret variable</a>.</blockquote>

```yaml
- task: AndroidSigning@2
  inputs:
    apkFiles: '**/*.apk'
    jarsign: true
    jarsignerKeystoreFile: 'pathToYourKeystoreFile'
    jarsignerKeystorePassword: '$(jarsignerKeystorePassword)'
    jarsignerKeystoreAlias: 'yourKeystoreAlias'
    jarsignerKeyPassword: '$(jarsignerKeyPassword)'
    zipalign: true
```
