### ISSUE TITLE
Automate deployment on the App Center

### ISSUE THREAD

**Issue by pnobbe** [Laixer/Swabbr-Android#58]
### App Center

Add the [App Center Distribute](../tasks/deploy/app-center-distribute.md) task to distribute an app to a group of testers or beta users,
or promote the app to Intune or Google Play. A free [App Center](https://appcenter.ms) account is required (no payment is necessary).

### Google Play

Install the [Google Play extension](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play)
and use the following tasks to automate interaction with Google Play. By default, these tasks authenticate to Google Play
using a [service connection](..//library/service-endpoints.md) that you configure.

#### Release

Add the [Google Play Release](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play#user-content-google-play---release)
task to release a new Android app version to the Google Play store.

```yaml
- task: GooglePlayRelease@2
  inputs:
    apkFile: '**/*.apk'
    serviceEndpoint: 'yourGooglePlayServiceConnectionName'
    track: 'internal'
```

#### Promote

Add the [Google Play Promote](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play#user-content-google-play---promote)
task to promote a previously-released Android app update from one track to another, such as `alpha` &rarr; `beta`.

```yaml
- task: GooglePlayPromote@2
  inputs:
    packageName: 'com.yourCompany.appPackageName'
    serviceEndpoint: 'yourGooglePlayServiceConnectionName'
    sourceTrack: 'internal'
    destinationTrack: 'alpha'
```

#### Increase rollout

Add the [Google Play Increase Rollout](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play#user-content-google-play---increase-rollout)
task to increase the rollout percentage of an app that was previously released to the `rollout` track.

```yaml
- task: GooglePlayIncreaseRollout@1
  inputs:
    packageName: 'com.yourCompany.appPackageName'
    serviceEndpoint: 'yourGooglePlayServiceConnectionName'
    userFraction: '0.5' # 0.0 to 1.0 (0% to 100%)
```
